name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: MANIFEST_URL
        required: true
        default: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
        type: choice
        options:
        - https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
        - https://github.com/SHRP-Reborn/manifest
        - https://github.com/PitchBlackRecoveryProject/manifest_pb
        - https://github.com/minimal-manifest-twrp/platform_manifest_twrp_lineageos
      MANIFEST_BRANCH:
        description: MANIFEST_BRANCH
        required: true
        default: twrp-12.1
        type: choice
        options:
        - twrp-12.1
        - twrp-14.1
        - twrp-11
        - shrp-12.1
        - v3_11.0
        - v3_10.0
        - android-12.1
        - android-11.0
      DEVICE_NAME:
        description: DEVICE_NAME
        required: true
        default: even
      BUILD_TARGET:
        description: BUILD_TARGET
        required: true
        default: recovery

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::Build Parameters"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v3

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python3

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '8'

    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Notify in Telegram
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="Build Started%0AManifest: ${{ github.event.inputs.MANIFEST_URL }}%0ABranch: ${{ github.event.inputs.MANIFEST_BRANCH }}%0ADevice: ${{ github.event.inputs.DEVICE_NAME }}%0ATarget: ${{ github.event.inputs.BUILD_TARGET }}" \
        -d parse_mode=html \
        -d disable_web_page_preview=true

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      id: pwd
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "rjfahad"
        git config --global user.email "asffghjjkk1971bangladesh@gmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}

    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - name: Clone device tree
      run: |
        git clone ${{ github.server_url }}/${{ github.repository }} -b ${{ github.ref_name }} ./device/realme/even
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Check Build Tree
      uses: haya14busa/action-cond@v1
      id: buildtree
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1' }}
        if_true: twrp
        if_false: omni

    - name: Sync Device Dependencies
      run: |
        bash ${GITHUB_WORKSPACE}/scripts/convert.sh device/realme/even/${{ steps.buildtree.outputs.value }}.dependencies 2>/dev/null || true
        repo sync -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export USE_CCACHE=1
        export CCACHE_COMPRESS=1
        export CCACHE_MAXSIZE=50G
        export TZ=Asia/Jakarta
        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng
        make clean
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Build finished Notify in Telegram
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="Build Finished%0ADevice: ${{ github.event.inputs.DEVICE_NAME }}%0ATarget: ${{ github.event.inputs.BUILD_TARGET }}" \
        -d parse_mode=html \
        -d disable_web_page_preview=true

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
